-- Migration 006: Workflow Checkpoints
-- Created: 2025-11-14
-- Purpose: Enable checkpoint/resume functionality for adaptive DAG workflows
-- Story: 2.5-2 Checkpoint & Resume (Epic 2.5)

-- Workflow checkpoint table: Stores WorkflowState snapshots for fault tolerance
CREATE TABLE IF NOT EXISTS workflow_checkpoint (
  -- Primary identifier: UUID v4 generated by crypto.randomUUID()
  id TEXT PRIMARY KEY,

  -- Workflow grouping: Links checkpoints to specific workflow instances
  workflow_id TEXT NOT NULL,

  -- Timestamp: Auto-generated for ordering and pruning
  timestamp TIMESTAMPTZ DEFAULT NOW(),

  -- Layer index: DAG layer number to resume from (0-indexed)
  layer INTEGER NOT NULL,

  -- State snapshot: WorkflowState serialized to JSONB
  -- Contains: { workflow_id, current_layer, messages[], tasks[], decisions[], context{} }
  state JSONB NOT NULL,

  -- Validation constraints
  CONSTRAINT chk_layer_non_negative CHECK (layer >= 0)
);

-- Index for fast pruning and latest checkpoint queries
-- Ordered by timestamp DESC to optimize "keep N most recent" queries
CREATE INDEX IF NOT EXISTS idx_checkpoint_workflow_ts
  ON workflow_checkpoint(workflow_id, timestamp DESC);

-- Index for workflow_id lookups (resume scenarios)
CREATE INDEX IF NOT EXISTS idx_checkpoint_workflow_id
  ON workflow_checkpoint(workflow_id);

-- Comments for schema documentation
COMMENT ON TABLE workflow_checkpoint IS
  'Stores WorkflowState snapshots for checkpoint/resume functionality. Retention: 5 most recent per workflow.';
COMMENT ON COLUMN workflow_checkpoint.state IS
  'JSONB serialization of WorkflowState (messages, tasks, decisions, context). Excludes filesystem state (documented limitation).';
