/**
 * Package Session Types
 *
 * Types for PML package registration and session management.
 * Enables handshake between package and server at startup.
 *
 * @module mcp/sessions/types
 */

/**
 * Package capabilities declared at registration.
 */
export interface PackageCapabilities {
  /** Can execute code in sandbox */
  sandbox: boolean;
  /** Can handle client-routed tools (filesystem, git, etc.) */
  clientTools: boolean;
  /** Supports hybrid routing (execute_locally) */
  hybridRouting: boolean;
}

/**
 * Registration request from package to server.
 */
export interface RegisterRequest {
  /** Unique client ID (generated by package, persisted locally) */
  clientId: string;
  /** Package version */
  version: string;
  /** Package capabilities */
  capabilities: PackageCapabilities;
  /** Workspace path (for context) */
  workspace?: string;
}

/**
 * Registration response from server to package.
 *
 * Note: routingConfig is NOT included - package syncs it separately
 * via syncRoutingConfig() at startup (Story 14.3 architecture decision).
 */
export interface RegisterResponse {
  /** Session ID for subsequent requests */
  sessionId: string;
  /** Session expiry (ISO timestamp) */
  expiresAt: string;
  /** Heartbeat interval in ms (how often to ping) */
  heartbeatIntervalMs: number;
  /** Feature flags from server */
  features: {
    hybridRouting: boolean;
    tracing: boolean;
  };
}

/**
 * Active package session stored on server.
 */
export interface PackageSession {
  /** Session ID */
  sessionId: string;
  /** Client ID (from package) */
  clientId: string;
  /** User ID (from auth) */
  userId: string;
  /** Package version */
  version: string;
  /** Package capabilities */
  capabilities: PackageCapabilities;
  /** Workspace path */
  workspace?: string;
  /** Registration timestamp */
  registeredAt: Date;
  /** Last heartbeat timestamp */
  lastHeartbeat: Date;
  /** Session expiry */
  expiresAt: Date;
}

/**
 * Heartbeat request from package.
 */
export interface HeartbeatRequest {
  sessionId: string;
}

/**
 * Heartbeat response from server.
 */
export interface HeartbeatResponse {
  /** Whether session is still valid */
  valid: boolean;
  /** New expiry time */
  expiresAt: string;
}

/**
 * Unregister request from package (graceful shutdown).
 */
export interface UnregisterRequest {
  sessionId: string;
}
